# Generated by Django 4.0.3 on 2024-07-18 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_orderdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.CharField(default='https://upload.wikimedia.org/wikipedia/commons/1/14/No_Image_Available.jpg', max_length=500),
        ),
    ]
